acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }

acme_hello_goodbye:
    pattern: /goodbye
    defaults: { _controller: AcmeHelloBundle:Hello:goodbye }
