parameters:
#    svdm_twitter.example.class: Svdm\TwitterBundle\Example

services:
#    svdm_twitter.example:
#        class: %svdm_twitter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
